"""Constant."""

IGNORE_REGEX_LIST = [
    r'.*HOISS.*',
    r'.*HHS.*',
    r'.*semmbomeSaqQo.*',
    r'.*Honomasenid.*',
    r'.*SAwwwy.*',
    r'.*\+94.*',
    r'.*163, Borgen.*',
    r'.*Age Group.*',
    r'.*Anexirenen novelas.*',
    r'.*ce.*mbme.*',
    r'.*cermmboe*',
    r'.*dasenrd.*',
    r'.*dasombd.*',
    r'.*Divulapitiya, Peliyagoda.*',
    r'.*Gender.*',
    r'.*GnroeH.*',
    r'.*Henew.*',
    r'.*Henes.*',
    r'.*HOasS.*',
    r'.*Honewtadaserd.*',
    r'.*semmbmeScs.*',
    r'.*Henesrasenid.*',
    r'.*INFECTIONS REPORTED.*',
    r'.*reported patients.*',
    r'.*Sly.*',
    r'.*SAm.*',
    r'.*novellas.*',
    r'\d{4}\.\d{2}\.\d{2}',
    r'© 163.*',
    r'103, Ageia ney, Gar',
    r'103, Dpexirrenen novelas, Ge',
    r'163, Dgerrionen osetia, a,',
    r'1g 05,4',
    r'70-79 years - Pal',
    r'AIFS HHUO HonowadHend',
    r'AIFS.*',
    r'AJF.*',
    r'Chief Editor.*News Editor',
    r'Department of Government Information',
    r'Details of the deceased',
    r'Director \(News\) / News Manage',
    r'Director General of Government .+nformation',
    r'Director.*News.*anager',
    r'G00, ore 0',
    r'Mohan Samaranayake',
    r'No of Covid Cases',
    r'ode .*',
    r'odes HOassg sembmeSadqoO',
    r'Press Release',
    r'Pwr > Ian',
    r'Release No: \d{3}/20\d{2}',
    r'S2omrnry, ord\)',
    r'Saw.*',
    r'Say.*',
    r'Sd.*',
    r'Sed HbHasS.*',
    r'Ses HOasS seembmeSes—O',
    r'Slow, ed\)',
    r'subject to the existing travel restrictions',
    r'SYsFTKis.*',
    r'SYsThs ZaHsucd Honemadsenid',
    r'Under 20 years - ol',
    r'Update',
    r'Slyw\., ed\) WRN\)',
    r'SPywwwy > Inn',
    r'Age group Female Male Total',
]
