name: Process https://www.dgi.gov.lk/news/press-releases-sri-lanka/covid-19-documents

on:
  schedule:
    - cron:  "58 * * * *"

jobs:
  run_cmd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Get version"
      id: get_version
      run: VERSION=$(python ./setup.py --version) && echo "::set-output name=VERSION::$VERSION" && echo "VERSION = $VERSION"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest

        sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config -y
        python -m pip install --upgrade pip
        pip install Cython
        pip install tesserocr

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Run
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/nopdf/custom_dgigovlk.py

    - name: Checkout nopdf_data
      uses: actions/checkout@v2
      with:
        repository: nuuuwan/nopdf_data
        token: "${{ secrets.NOPDF_DATA_TOKEN}}"

    - name: Copy data, and push to nopdf_data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp /tmp/nopdf* .
        git add .
        git commit -m "Updated data $(date)"
        git push origin main
