on: workflow_dispatch

jobs:
  run_cmd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Get version"
      id: get_version
      run: VERSION=$(python ./setup.py --version) && echo "::set-output name=VERSION::$VERSION" && echo "VERSION = $VERSION"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'



    - name: Run
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        echo 'test' > /tmp/nopdf.test.txt

    - name: Checkout nuuuwan/nopdf_data
      uses: actions/checkout@v2
      with:
        repository: nuuuwan/nopdf_data
        token: "${{ secrets.NOPDF_DATA_TOKEN }}"


    - name: Copy data
      run: |
        echo '....'
        echo 'Running: ls'
        ls
        echo '....'
        echo 'Running: ls /tmp/'
        ls /tmp/nopdf*
        echo '....'

        echo 'Settting git config...'
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

        echo 'Copying files...'
        cp /tmp/nopdf* .

        echo 'Git add, commit and push...'
        git add .
        git commit -m "Added new data"
        git push origin main
