on: workflow_dispatch

jobs:
  run_cmd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Get version"
      id: get_version
      run: VERSION=$(python ./setup.py --version) && echo "::set-output name=VERSION::$VERSION" && echo "VERSION = $VERSION"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest

        sudo apt-get install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config -y
        python -m pip install --upgrade pip
        pip install Cython
        pip install tesserocr

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Run
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/nopdf/custom_dgigovlk.py
        ls /tmp/

    - name: Checkout nuuuwan/nopdf_data
      uses: actions/checkout@v2
      with:
        repository: nuuuwan/nopdf_data


    - name: Copy data
      run: |
        echo '....'
        echo 'Running: ls'
        ls
        echo '....'
        echo 'Running: ls /tmp/'
        ls /tmp/
        echo '....'
        cp /tmp/nopdf* .

        git config --global user.email "${{ secrets.GITHUB_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GITHUB_USER_NAME }}"
        git add .
        git commit -m "Added new data"
        git push origin main
